In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd
import time

# Corrigido aqui 👇
service = Service(ChromeDriverManager().install())
driver = webdriver.Chrome(service=service)

In [ ]:
import pandas as pd
from sqlalchemy import create_engine

# conexão
engine = create_engine(
    "mysql+pymysql://root:senha@localhost:3306/RECLAMEAQUI_CONSORCIO"
)
df = pd.read_sql("SELECT * FROM reclamacoes", con=engine)
display(df)

,id,titulo,link
0,5,Demora excessiva e falta de informação no proc...,https://www.reclameaqui.com.br/consorcio-fiat-...
1,6,Cobrança Indevida e Falta de Resposta Após Can...,https://www.reclameaqui.com.br/consorcio-fiat-...
2,7,Itaú Unibanco / Consórcio Itaú: Recusa de Tran...,https://www.reclameaqui.com.br/consorcio-fiat-...
3,8,Consórcio Itaú recusa todo mundo - sistema de ...,https://www.reclameaqui.com.br/consorcio-fiat-...
4,9,Cobrança indevida de valores não autorizados e...,https://www.reclameaqui.com.br/consorcio-fiat-...
...,...,...,...
205,210,Consórcio Banco Itaú: Cobrança de taxas e demo...,https://www.reclameaqui.com.br/consorcio-fiat-...
206,211,Fui pressionado a fechar consórcio de investim...,https://www.reclameaqui.com.br/consorcio-fiat-...
207,212,Cobrança de multa e juros após reativação de c...,https://www.reclameaqui.com.br/consorcio-fiat-...
208,213,Cancelamento de consórcio Itau por atraso no p...,https://www.reclameaqui.com.br/consorcio-fiat-...
209,214,Solicitação de informe de rendimentos unificad...,https://www.reclameaqui.com.br/consorcio-fiat-...

In [3]:
lista_links = df['link'].to_list()
lista_links

['https://www.reclameaqui.com.br/consorcio-fiat-e-itau/demora-excessiva-e-falta-de-informacao-no-processo-de-transferencia-de-titularidade-de-consorcio-resultando-em-risco-de-perda-de-negocio_I4xiLCnb0Tc8Uqfx/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cobranca-indevida-e-falta-de-resposta-apos-cancelamento-de-consorcio-itau_T2RMN2V4KxzQJ1r8/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/itau-unibanco-consorcio-itau-recusa-de-transferencia-de-cotas-contempladas-sem-justificativa-plausivel-e-falta-de-resolucao_CMwamVZDsohoRBZB/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-itau-recusa-todo-mundo-sistema-de-analise-de-credito-bugado_q3_1BafRx-S8E3Eg/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cobranca-indevida-de-valores-nao-autorizados-em-boleto-de-quitacao-de-consorcio_EPi-RIaWiL9DBtUf/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/solicitacao-de-cancelamento-de-consorcio-titulo-de-capitalizacao-e-seguro-de-vida-com-recusa-de-devolucao-do-valor-pago_2BM3_QKTD-hWN3ZI/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cobranca-indevida-e-falta-de-informacao-clara-sobre-contrato_Gk6VBXX859ivIDz4/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/nao-enviam-o-boleto-de-consorcio-por-email_g13kVdC7-3ETg---/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/reembolso-de-valor-pago-nao-realizado-descumprindo-prazo-estipulado_mXtbnsQGsZnzdkvg/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/problemas-de-visualizacao-de-lance-no-aplicativo-itau-e-mau-atendimento-nos-canais-de-suporte_c1VcXgVPrxgnzEhB/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/saldo-devedor-incorreto-em-consorcio-imobiliario-apos-quitacao-com-financiamento-caixa_CZPl4mF_2UxNpM6-/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/comprovante-pagamento-consorcio-automovel_VsrTHiuFQ47g3jeg/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/impossibilidade-de-obter-declaracao-de-parcelas-pagas-para-venda-de-consorcio-no-itau_kb44-ejkI1KZrIeQ/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/reclamacao-sobre-carro-com-multiplos-defeitos-e-problemas-com-devolucao-de-valor-apos-8-meses-de-tentativas-de-conserto-vinculado-a-carta-de-credito-itau-que-nunca-foi-entregue_JAhGI9iJRqMjjtBr/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/viuva-tenta-receber-valor-de-consorcio-apos-falecimento-do-marido-ha-meses-sem-sucesso-e-com-muita-dificuldade-de-contato-com-a-empresa_CV-oHaUgZ9hUQSCe/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-uso-do-saldo-restante-do-carro_xS2IzigcH4Z7O_4-/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/itau-consorcios-se-recusa-a-fornecer-copia-do-contrato-e-do-regulamento_xcF6pcwJOLRy8KWA/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/informacoes-divergentes-sobre-utilizacao-de-carta-de-credito-em-consorcio-itau_fje-95A8PoG2bA0o/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-itau-desistencia-em-e-nao-devolucao-do-valor-pago_FzW0JZxi-khWyeu1/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/valor-de-restituicao-de-consorcio-cancelado-muito-abaixo-do-total-pago-cota-de-excluido_vzuTc_vxepD6TQ07/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/transferencia-de-titularidade-de-consorcio-de-veiculo-contemplado-com-atraso-e-descumprimento-de-prazo-pelo-consorcio-itau_h5BMkYHSggCsLr7u/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-itau-erro-no-sistema-impede-uso-de-carta-de-credito-quitada-ha-15-dias-gerando-transtorno_0neC6rENNsOqLwMD/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/banco-itau-cobranca-indevida-e-falta-de-estorno-de-boleto-pago-em-duplicidade_k_BohrWx4rYqUM9E/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/dificuldade-em-obter-contrato-de-consorcio-imobiliario-para-acionar-seguro-sem-sucesso-pelo-chat-do-aplicativo_YS8Ymd4G-h7LKF-e/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/empresa-engana-clientes-com-promessas-de-investimento-e-oferece-reparacao-irrisoria_RKDAMQQynLFvl7aR/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/demora-no-envio-do-boleto-de-consorcio-demorando-mais-que-o-normal_pKSXRc4k73tOP9ex/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-itau-cobranca-indevida-de-50-em-cancelamento-e-exigencia-de-devolucao-conforme-lei_l2Tsg-CCfWj2swrk/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/impossibilidade-de-restituicao-de-fundo-de-reserva-de-consorcio-com-saldo-a-receber-apesar-de-grupos-encerrados_fqSdxk0GmBREZDqt/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/duvidas-sobre-assembleias-contemplacoes-e-lances-em-consorcio-itau-com-atas-incorretas-e-falta-de-esclarecimentos_jVFsk2HIQ5XAAVfs/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/pagamento-estornado-do-meu-consorcio-contemplado-por-sorteio_0WrLsjqZ_k80chzo/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/atraso-na-transferencia-de-cota-de-consorcio-itau-necessidade-urgente-para-aquisicao-de-veiculo_z62D1V7RZR_ZM8rt/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/impossibilidade-de-contato-com-o-setor-de-consorcio-do-banco-itau-valores-a-receber_JoxKy5yCY72JbXx_/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/prazo-de-boleto-de-quitacao-invalido-para-processo-de-seguro-pos-acidente_7Pkf3NbnMA-MPWmF/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/reserva-de-cota-de-consorcio-feito-sem-autorizacao-da-cliente_S5QQURnznf3Nz5tn/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/impossibilidade-de-utilizar-carta-de-credito-de-consorcio-para-compra-de-veiculo-pcd-em-nome-de-filha-menor-de-idade_FuYUA2K-ZIKPL8zP/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/insatisfacao-com-atendimento-e-dificuldade-no-cancelamento-de_B9viaXt7A-b71emn/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cobranca-indevida-de-consorcio-e-dificuldade-no-estorno-de-valor-pago_4PnopMlFFGcYNH5w/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/contemplacao-de-consorcio-nao-confirmada-pelo-banco-apos-informacao-do-aplicativo_uZFOFwsBYierYoaf/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/impossibilidade-de-acesso-ao-extrato-de-consorcio-detalhado-e-falha-no-atendimento-ao-cliente_7e9k1c47nUhF2tJ4/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/demora-e-falta-de-resposta-no-processo-de-transferencia-de-cota-contemplada-itau_Z7Oi8B9IezfmBaWO/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/banco-itau-devolucao-de-valor-prometida-mas-detalhes-da-operacao-nao-clarificados-gerando-invasao-de-privacidade_f5QzF51YwbtmIz5M/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cancelamento-indevido-de-consorcio-pelo-itau-sem-autorizacao-e-recusa-de-devolucao-integral-dos-valores-pagos_E536iB5_H4HdDTOT/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-imobiliario-prejuizo-financeiro-e-longa-espera-na-restituicao_PfCNN9wfsGByvH--/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/dificuldade-de-acesso-ao-portal-do-consorcio-itau-devido-a-credenciais-invalidas-com-risco-de-cobranca-de-juros_exJ2AoMIxr341RVq/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-empresa-se-recusa-a-devolver-valor-antes-do-fim-do-grupo-descumprindo-a-lei_5P0wkhBokg_wYVgW/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/carta-contemplada-e-dificuldade-em-realizar-a-utilizacao-informacoes-divergentes-da-central-de-atendimento_YxgyQmeLkVuONqMC/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cobranca-indevida-de-consorcio-nao-autorizado-e-falta-de-estorno__WmExpG6LXJIsvUH/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-imobiliario-itau-negativa-de-informacoes-sobre-contemplacoes-do-grupo_jB0Lc4b9BaGDyaJO/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-itau-falta-de-informacao-sobre-restricao-no-bacen-resultou-em-recusa-e-perda-financeira_-rkDHbc26O5aORpY/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/itau-consorcios-cobranca-abusiva-e-na-aplicacao-de-taxas-apos-cancelamento-dentro-do-prazo-contratual_rttpW__FppNH3yyG/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cobranca-indevida-de-banco-cliente-relata-descaso-e-falta-de-solucao-para-problema-habitacional-apos-10-anos_6qlfOqkHSYxEkceX/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/alerta-sobre-consorcio-itau-burocracia-excessiva-na-contemplacao-da-carta-de-credito_RpdL3YT49DyoJ93x/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cancelamento-indevido-de-consorcio-por-falta-de-contato-e-erro-cadastral_pInMy3h6x2vWuKki/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-promessa-de-reducao-de-parcela-no-app-nao-cumprida-gera-cobranca-excessiva-e-engano-ao-consumidor_2SacQCRG794kNZQM/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/reclamacao-formal-publicidade-enganosa-e-intermediacao-em-contrato-de-consorcio-itau-pela-adm_tEz9Dpw0VrKSDMTx/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/resgate-de-3-consorcio-banco-nao-consegue-me-devolver_qIcceDrmVK7AFFMd/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/itau-dificuldade-de-contato-e-falta-de-retorno-sobre-consorcio-mesmo-apos-contato-com-sac-e-ouvidoria_LLH9hD8uTVxEecTS/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cobranca-indevida-em-consorcio-de-imovel_yP7PAXMppnRXOZhX/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-de-motocicleta-itau-informacoes-contraditorias-e-abusivas-sobre-desistencia-e-retencao-de-valores_Udvqth21iPmDhKh3/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/informacoes-sobre-consorcio-con-cnpj-baixado_r-aOTZ-3yDLSie3B/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-itau-quitacao-de-consorcio-sem-baixa-de-gravame-no-detran_SoehnBn-tNm9RI_T/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/reclamacao-sobre-anuencia-para-transferencia-de-imovel-em-consorcio-itau-consorcio_yR-voLWXG_0MQswV/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cobra-taxa-de-avaliacao-indevida-para-veiculo-zero-km_QqeLv2A4Zh14KI7e/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-valor-de-resgate-inferior-ao-pago-solicito-investigacao_H58_LoAjzaFKOHQT/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/erro-na-sequencia-registral-faturamento-de-veiculo-impossivel_Oe99DV8Kpuo78Igy/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cobranca-indevida-apos-pagamento-e-dificuldade-de-resolucao-com-o-banco_KwMSaI5e_YU6sgsh/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cobranca-de-multa-e-taxa-administrativa-indevida-em-cancelamento-de-consorcio-imobiliario-por-venda-mal-feita_lz1P35tI2yAnYRSG/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/dificuldade-em-obter-informe-de-rendimento-para-imposto-de-renda-apos-promessa-de-envio-por-e-mail-nao-cumprida-e-falhas-no-atendimento-telefonico_QOSS-HcB8X-_f3w9/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/banco-retem-r-479-mil-apos-falecimento-descumpre-prazos-do-banco-central-e-ignora-familia_8O_JnD-Rln6ljVba/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/vendedor-promete-contemplacao-e-empresa-nao-reconhece-ma-conduta-mesmo-com-provas_SaQDg5-IJWT48QVl/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/dificuldade-em-encerrar-conta-pj-e-migrar-debitos-apos-mau-atendimento-no-banco-itau_gDMlv1P2uggsFWzL/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/problemas-com-a-transferencia-de-documento-de-veiculo-apos-quitacao-de-consorcio-itau_mLu8L5vmajMOKVLi/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/demora-na-substituicao-de-garantia-e-baixa-de-gravame-com-prazos-excedidos-e-falta-de-solucao-pela-central-de-atendimento_M7p1VthhI0xQ2PBR/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/dificuldade-na-reativacao-de-consorcio-informacoes-inconsistentes-e-desculpas-diarias-dos-atendentes-bancarios_Z20hK6tstS2Mzs6l/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-contemplado-mas-banco-alega-nao-constar-no-sistema-e-nega-deposito_yMDxSTbbFkg6ioj2/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/restricao-de-alienacao-fiduciaria-indevida-no-detran-apos-quitacao-de-divida-com-o-itau_apVUD1cDOlAWg4UI/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/demora-na-conclusao-da-substituicao-de-garantia-e-baixa-de-gravame_CYx1uT4m3d5BVMzY/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/problemas-na-venda-de-imovel-via-consorcio-itau-falta-de-comunicacao-e-atrasos-no-processo-de-interveniente-quitante_br_W6KDrHO8f1rbl/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-itau-informacao-de-contemplacao-incorreta-no-aplicativo-gera-insatisfacao_ynmj-wq8SBCXFasE/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/falha-na-comunicacao-de-contemplacao-de-consorcio-e-recusa-de-aprovacao-de-credito-para-aquisicao-de-veiculo_i9VFE1q203JIZrlZ/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/insatisfacao-com-consorcio-e-atendimento-no-banco-itau_NQY2u3eXe_46FWbU/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/itau-consorcio-erro-no-nome-impede-transferencia-de-veiculo-no-detran-rj_9MGtFSriVg1A6RjW/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/retencao-abusiva-de-valores-pagos-no-consorcio-itau-apos-cancelamento_QOPL1OsaGMYqzA62/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-itau-realizou-o-cancelamento-de-cota-sem-aviso-previo-ao-consorciado_NhP11FlXiK1xLXt0/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/insatisfacao-com-o-atendimento-do-itau-personnalite-na-substituicao-de-garantia-de-consorcio-com-taxas-ja-debitadas-e-falta-de-retorno_uX0aynF2pfM662Wx/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/solicitacao-de-transferencia-de-cota-mediante-procuracao-para-nao-correntista_3rZjziCaqrThoFFB/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/contratacao-de-consorcio-com-informacoes-enganosas-e-cobranca-indevida-itau-unibanco_MCJGHy38Dx49BMNh/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/venda-casada-ao-abrir-conta-pj-contratacao-indevida-na-pessoa-fisica-e-prejuizo-financeiro_fOoE8QgKFjE7lcXz/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/itau-consorcio-quer-reter-mais-de-50-do-meu-dinheiro-sem-transparencia_s-B6f9gb1LKlFz-E/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cobranca-indevida-e-informacoes-enganosas-sobre-consorcio-imobiliario-itau_UIExllOuIgIIF4QX/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/itau-consorcio-cancelamento-de-transferencia-de-cotas-sem-justificativa-plausivel-apos-meses-de-processo-e-cumprimento-de-etapas_5a5czd47A4LJLtdT/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/solicitacao-de-gravacao-de-ligacao-de-consorcio-divergencia-de-informacoes-sobre-lance-embutido__5XAbiaNa9VDiZhk/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/descumprimento-contratual-e-prejuizos-financeiros-pelo-banco-itau-e-protech-consorcios-no-fracionamento-de-carta-de-credito_iUMSola_CA7a7HFt/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cobranca-alterada-sem-aviso-negativacao-indevida-mesmo-com-saldo-disponivel_e2aDRT8K-sBRVRBd/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/solicitacao-de-ressarcimento-de-valores-faltantes-em-consorcio_bdt5Y5ehjqFcCuKO/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/propaganda-enganosa-e-falta-de-transparencia-em-cota-de-consorcio-com-promessa-de-devolucao-imediata_AAntVyeZfZBR-rUn/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/impossibilidade-de-simular-consorcio-pelo-aplicativo-ha-um-mes_IBNQhTbbUMlnD515/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-dificuldade-na-compra-de-moto-contemplada-com-perda-de-desconto-devido-a-falhas-no-sistema-e-mau-atendimento_0G5Xnqxu_PVYVqc0/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cancelamento-de-consorcio-e-estorno-de-dinheiro-nao-realizado-apos-uma-semana_FRFRSWUe7asUE0pd/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-itau-se-recusa-a-emitir-carta-de-contemplacao-gerando-risco-de-multa-e-prejuizo-financeiro-para-cliente_ybRVMThq52aTb_5C/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/veiculo-quitado-em-consorcio-pelo-itau-continua-alienado-no-detran-es-e-canais-de-atendimento-nao-resolvem_rPvmClp8OxEyxpNT/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/imovel-itau-consorcios-demora-na-devolucao-de-valores-pagos-de-consorcio-imobiliario-cancelado-em-2011_705c0qBdpKAAaGRB/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-itau-erro-em-agencia-atraso-na-liberacao-de-credito-apos-contemplacao_LX0n-US4uSBhm7_1/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/liberacao-indevida-de-credito-de-consorcio-e-inclusao-irregular-de-gravame-pelo-banco-itau_JIAvCSLhHL_jHZfD/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/itau-consorcio-dificuldade-na-liberacao-de-venda-de-cartas-de-credito-mesmo-com-comprador-idoneo_ed1xE3-Y8ekwEhtc/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cliente-solicita-estorno-de-consorcio-imobiliario-nao-contratado-e-nao-reconhecido_vSgdHh04TDwztIfm/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/banco-itau-falha-na-prestacao-de-servico-e-demora-na-analise-de-solicitacao-de-consorcio_MT0QaSbPUce96Voq/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/impossibilidade-de-obter-extrato-de-cota-de-consorcio-e-senha-bloqueada-no-app-do-banco_gZHpYqXQRqCHSYO6/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/solicitacao-de-devolucao-de-valor-pago-em-consorcio-itau-apos-inadimplencia_IZ0h3ZWYEu7fqb3C/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/demora-excessiva-e-falta-de-retorno-em-processos-de-transferencia-de-cotas-de-consorcio-junto-ao-itau_aTIpL3mmqwzRCXnV/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/banco-itau-retendo-74-do-valor-pago-em-consorcio-de-veiculo-apos-solicitacao-de-cancelamento_CU9Y7h_z467-WiCt/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cobranca-indevida-de-valor-para-compra-de-casa-sem-notificacao-e-dificuldade-de-estorno_WJFxJ0AMiE9xtUqV/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/nao-consigo-administrar-o-consorcio-pelo-aplicativo_Hgm34GEqgU2BK7j-/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/falta-de-analise-e-retorno-adequado-as-solicitacoes-sobre-consorcio_OsWEgCW4lrZ1CaoF/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/itau-unibanco-falta-de-repasse-de-dinheiro-de-consorcio-cancelado-e-contemplado-por-sorteio_iUKBXa9CWpsjZfUQ/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/demora-na-baixa-do-gravame-de-consorcio-quitado-pelo-itau-consorcio-impedindo-a-venda-do-veiculo_QPdaqEH8fhusptXq/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/taxa-administrativa-abusiva-em-consorcio-de-veiculo-e-restricao-de-idade-do-bem_X1uHLQtjluiGQvMl/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/dificuldade-na-utilizacao-do-fgts-para-abatimento-de-parcela-de-consorcio-itau_Hm554wCdtR0iGCMd/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/imovel-com-defeito-cobranca-indevida-apos-quitacao-de-consorcio-e-atraso-na-baixa-do-gravame_8KvzICpUZj-oU7e_/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/demora-na-baixa-de-gravame-de-consorcio-quitado-de-moto-apreendida_hnUKsZcocEFE3YbY/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/solicitacao-de-esclarecimentos-sobre-cobranca-de-tarifa-de-avaliacao-de-bem-sem-comprovacao-de-servico-prestado_LOYcrjB0k07Sey2K/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-nao-cobre-moto-off-road-apesar-de-contemplacao-por-lance-cliente-se-sente-enganado_RhoHScB6t90Gzece/',

In [ ]:
import time
import random
import undetected_chromedriver as uc

from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

driver = uc.Chrome(version_main=148)
wait = WebDriverWait(driver, 15)

try:
    for url in lista_links:
        dados = []
        print(f"Acessando {url}...")
        driver.get(url)

        wait.until(
            EC.presence_of_all_elements_located((By.TAG_NAME, "p"))
        )

        time.sleep(random.uniform(3, 6))
        elementos = driver.find_elements(By.TAG_NAME, "p")

        for el in elementos:
            texto = el.text.strip()
            if texto and len(texto) > 10:
                dados.append({
                    "texto": texto
                })

        # display(dados)
        palavras_lixo = [
            "compartilhe",
            "está com problema",
            "qual a posição",
            "lista de melhores",
            "confira a classificação",
            "área restrita",
            "acesse aqui",
            "conteúdos destinados",
            "classificação indicativa"
        ]

        registro = {
            "link": url,
            "ds_situacao_reclamacao": None,
            "estado_reclamacao": None,
            "data_reclamacao": None,
            "id_reclamacao": None,
            "descricao_reclamacao": None
        }

        for d in dados:
            texto = d["texto"].lower()

            # 🔥 remove lixo
            if any(p in texto for p in palavras_lixo):
                continue

            # status
            if "respondida" in texto:
                registro["ds_situacao_reclamacao"] = texto

            # estado (curto)
            elif " - " in texto and len(texto) < 50:
                registro["estado_reclamacao"] = texto

            # data
            elif "/" in texto and "às" in texto:
                registro["data_reclamacao"] = texto

            # id
            elif "id:" in texto:
                registro["id_reclamacao"] = texto.replace("id: ", "")

            # descrição (texto grande real)
            elif len(texto) > 100:
                registro["descricao_reclamacao"] = texto
            
            # descrição (texto grande real respondido pela empresa )
            elif len(texto) > 100:
                registro["descricao_reclamacao"] = texto
            
        df = pd.DataFrame([registro])
        # display(df)
        
        from sqlalchemy import create_engine
        engine = create_engine(
            "mysql+pymysql://root:senha@localhost:3306/RECLAMEAQUI_CONSORCIO"
        )

        # envio
        df.to_sql(
            name="reclamacoes_detalhe",
            con=engine,
            if_exists="append",
            index=False
        )
        print("Dados enviados com sucesso!")
        display(df)

finally:
    driver.quit()

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/demora-excessiva-e-falta-de-informacao-no-processo-de-transferencia-de-titularidade-de-consorcio-resultando-em-risco-de-perda-de-negocio_I4xiLCnb0Tc8Uqfx/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,são paulo - sp,21/05/2026 às 19:18,249338567,aproximadamente 40 dias dei entrada no process...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cobranca-indevida-e-falta-de-resposta-apos-cancelamento-de-consorcio-itau_T2RMN2V4KxzQJ1r8/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,embu das artes - sp,22/05/2026 às 15:15,249259517,no dia 14 de abril realizei o cancelamento do ...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/itau-unibanco-consorcio-itau-recusa-de-transferencia-de-cotas-contempladas-sem-justificativa-plausivel-e-falta-de-resolucao_CMwamVZDsohoRBZB/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,uberlândia - mg,22/05/2026 às 15:15,249317467,"prezados, registro reclamação grave contra o s..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-itau-recusa-todo-mundo-sistema-de-analise-de-credito-bugado_q3_1BafRx-S8E3Eg/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,uberlândia - mg,22/05/2026 às 15:15,249312413,None

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cobranca-indevida-de-valores-nao-autorizados-em-boleto-de-quitacao-de-consorcio_EPi-RIaWiL9DBtUf/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,contagem - mg,22/05/2026 às 15:15,249218095,três meses atrás adquiri um veículo cujo consó...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/solicitacao-de-cancelamento-de-consorcio-titulo-de-capitalizacao-e-seguro-de-vida-com-recusa-de-devolucao-do-valor-pago_2BM3_QKTD-hWN3ZI/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,joão pinheiro - mg,21/05/2026 às 09:23,248989195,"não quero mais o consórcio, título de capitali..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cobranca-indevida-e-falta-de-informacao-clara-sobre-contrato_Gk6VBXX859ivIDz4/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,belo horizonte - mg,20/05/2026 às 15:54,247790117,o dia inteiro recebendo [editado pelo reclame ...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/nao-enviam-o-boleto-de-consorcio-por-email_g13kVdC7-3ETg---/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,belo horizonte - mg,22/05/2026 às 15:15,249181869,já pedi algumas vezes para alterar o recebimen...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/reembolso-de-valor-pago-nao-realizado-descumprindo-prazo-estipulado_mXtbnsQGsZnzdkvg/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,salvador - ba,22/05/2026 às 15:15,249159709,quero a devolução do valor e nada foi feito ai...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/problemas-de-visualizacao-de-lance-no-aplicativo-itau-e-mau-atendimento-nos-canais-de-suporte_c1VcXgVPrxgnzEhB/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,osasco - sp,22/05/2026 às 15:15,249113927,adquiri um consórcio de veículo há três meses....

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/saldo-devedor-incorreto-em-consorcio-imobiliario-apos-quitacao-com-financiamento-caixa_CZPl4mF_2UxNpM6-/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,piracicaba - sp,19/05/2026 às 19:14,249121401,"tenho um apt no consorcio do itaú, fiz a venda..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/comprovante-pagamento-consorcio-automovel_VsrTHiuFQ47g3jeg/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,None,None,None,este site utiliza um serviço de segurança para...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/impossibilidade-de-obter-declaracao-de-parcelas-pagas-para-venda-de-consorcio-no-itau_kb44-ejkI1KZrIeQ/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,None,None,None,este site utiliza um serviço de segurança para...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/reclamacao-sobre-carro-com-multiplos-defeitos-e-problemas-com-devolucao-de-valor-apos-8-meses-de-tentativas-de-conserto-vinculado-a-carta-de-credito-itau-que-nunca-foi-entregue_JAhGI9iJRqMjjtBr/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,None,None,None,este site utiliza um serviço de segurança para...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/viuva-tenta-receber-valor-de-consorcio-apos-falecimento-do-marido-ha-meses-sem-sucesso-e-com-muita-dificuldade-de-contato-com-a-empresa_CV-oHaUgZ9hUQSCe/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,None,None,None,este site utiliza um serviço de segurança para...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-uso-do-saldo-restante-do-carro_xS2IzigcH4Z7O_4-/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,None,None,None,este site utiliza um serviço de segurança para...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/itau-consorcios-se-recusa-a-fornecer-copia-do-contrato-e-do-regulamento_xcF6pcwJOLRy8KWA/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,são paulo - sp,18/05/2026 às 08:38,248922979,sou titular de uma cota de consórcio imobiliár...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/informacoes-divergentes-sobre-utilizacao-de-carta-de-credito-em-consorcio-itau_fje-95A8PoG2bA0o/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,são paulo - sp,22/05/2026 às 15:15,248889385,None

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-itau-desistencia-em-e-nao-devolucao-do-valor-pago_FzW0JZxi-khWyeu1/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,indaiatuba - sp,22/05/2026 às 15:15,248863303,"em ***** eu fiz um consórcio do *****, paguei ..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/valor-de-restituicao-de-consorcio-cancelado-muito-abaixo-do-total-pago-cota-de-excluido_vzuTc_vxepD6TQ07/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,japeri - rj,22/05/2026 às 15:15,248550201,"olá,\nsou titular da cota de consórcio (grupo:..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/transferencia-de-titularidade-de-consorcio-de-veiculo-contemplado-com-atraso-e-descumprimento-de-prazo-pelo-consorcio-itau_h5BMkYHSggCsLr7u/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,uberlândia - mg,21/05/2026 às 15:00,248782631,"prezado,\n\nprimeiramente, agradecemos a oport..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-itau-erro-no-sistema-impede-uso-de-carta-de-credito-quitada-ha-15-dias-gerando-transtorno_0neC6rENNsOqLwMD/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,goiânia - go,22/05/2026 às 15:15,248663753,consórcio itaú - erro no sistema impede uso de...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/banco-itau-cobranca-indevida-e-falta-de-estorno-de-boleto-pago-em-duplicidade_k_BohrWx4rYqUM9E/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,são caetano do sul - sp,22/05/2026 às 15:15,248578227,"no dia ***** (sábado), realizei o pagamento de..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/dificuldade-em-obter-contrato-de-consorcio-imobiliario-para-acionar-seguro-sem-sucesso-pelo-chat-do-aplicativo_YS8Ymd4G-h7LKF-e/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,rio de janeiro - rj,22/05/2026 às 15:15,248642541,estou tentando obter o contrato do consórcio i...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/empresa-engana-clientes-com-promessas-de-investimento-e-oferece-reparacao-irrisoria_RKDAMQQynLFvl7aR/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,cambuquira - mg,15/05/2026 às 10:03,248607723,corram desta empresa.\nfomos [editado pelo rec...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/demora-no-envio-do-boleto-de-consorcio-demorando-mais-que-o-normal_pKSXRc4k73tOP9ex/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,muriaé - mg,20/05/2026 às 09:34,248721859,"dessa vez atrasaram na resposta, por isso vou ..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-itau-cobranca-indevida-de-50-em-cancelamento-e-exigencia-de-devolucao-conforme-lei_l2Tsg-CCfWj2swrk/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,são paulo - sp,22/05/2026 às 15:15,248697829,sou titular de 2 cotas no consórcio itaú:\n1. ...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/impossibilidade-de-restituicao-de-fundo-de-reserva-de-consorcio-com-saldo-a-receber-apesar-de-grupos-encerrados_fqSdxk0GmBREZDqt/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,salvador - ba,22/05/2026 às 15:15,248692371,possuo 2 consórcios com o ***** em grupos já e...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/duvidas-sobre-assembleias-contemplacoes-e-lances-em-consorcio-itau-com-atas-incorretas-e-falta-de-esclarecimentos_jVFsk2HIQ5XAAVfs/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,None,22/05/2026 às 15:15,248674959,"tenho um consórcio, sou cliente a mais de 15 a..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/pagamento-estornado-do-meu-consorcio-contemplado-por-sorteio_0WrLsjqZ_k80chzo/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,recife - pe,22/05/2026 às 15:15,248668283,recebi uma mensagem do consórcio itaú via what...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/atraso-na-transferencia-de-cota-de-consorcio-itau-necessidade-urgente-para-aquisicao-de-veiculo_z62D1V7RZR_ZM8rt/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,nova ponte - mg,22/05/2026 às 15:15,248657783,*atraso no processo de transferência no consór...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/impossibilidade-de-contato-com-o-setor-de-consorcio-do-banco-itau-valores-a-receber_JoxKy5yCY72JbXx_/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,são paulo - sp,22/05/2026 às 15:15,248611635,bom dia. estou tentando contato com o setor de...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/prazo-de-boleto-de-quitacao-invalido-para-processo-de-seguro-pos-acidente_7Pkf3NbnMA-MPWmF/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,palmeira - pr,22/05/2026 às 15:15,248593189,"tenho um consórcio de veículo com o ***** e, i..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/reserva-de-cota-de-consorcio-feito-sem-autorizacao-da-cliente_S5QQURnznf3Nz5tn/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,são paulo - sp,13/05/2026 às 18:33,248529161,entrei em contato para apenas consultar as opç...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/impossibilidade-de-utilizar-carta-de-credito-de-consorcio-para-compra-de-veiculo-pcd-em-nome-de-filha-menor-de-idade_FuYUA2K-ZIKPL8zP/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,são francisco de itabapoana - rj,22/05/2026 às 15:15,248569773,"fiz um consórcio com o *****, fui contemplado ..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/insatisfacao-com-atendimento-e-dificuldade-no-cancelamento-de_B9viaXt7A-b71emn/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,rio de janeiro - rj,19/05/2026 às 09:56,248558667,"prezada,\n\nprimeiramente, agradecemos a oport..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cobranca-indevida-de-consorcio-e-dificuldade-no-estorno-de-valor-pago_4PnopMlFFGcYNH5w/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,salvador - ba,22/05/2026 às 15:15,248479437,"a minha reclamação é sobre uma *****, a 5 mese..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/contemplacao-de-consorcio-nao-confirmada-pelo-banco-apos-informacao-do-aplicativo_uZFOFwsBYierYoaf/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,pelotas - rs,22/05/2026 às 15:15,248540505,fui informada pelo app do banco que meu consor...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/impossibilidade-de-acesso-ao-extrato-de-consorcio-detalhado-e-falha-no-atendimento-ao-cliente_7e9k1c47nUhF2tJ4/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,são paulo - sp,22/05/2026 às 15:15,248444587,não consigo pelo app e nem pela web o extrato ...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/demora-e-falta-de-resposta-no-processo-de-transferencia-de-cota-contemplada-itau_Z7Oi8B9IezfmBaWO/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,None,22/05/2026 às 15:15,247409245,"prezados,\npreciso que transfiram a cota conte..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/banco-itau-devolucao-de-valor-prometida-mas-detalhes-da-operacao-nao-clarificados-gerando-invasao-de-privacidade_f5QzF51YwbtmIz5M/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,salvador - ba,22/05/2026 às 15:15,248373439,o banco itau informou que até dia ***** será d...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cancelamento-indevido-de-consorcio-pelo-itau-sem-autorizacao-e-recusa-de-devolucao-integral-dos-valores-pagos_E536iB5_H4HdDTOT/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,brasília - df,22/05/2026 às 15:15,248351779,"boa noite.\n\nvenho, por meio desta, registrar..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-imobiliario-prejuizo-financeiro-e-longa-espera-na-restituicao_PfCNN9wfsGByvH--/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,são gonçalo - rj,22/05/2026 às 15:15,248322605,consórcio imobiliário *****: prejuízo financei...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/dificuldade-de-acesso-ao-portal-do-consorcio-itau-devido-a-credenciais-invalidas-com-risco-de-cobranca-de-juros_exJ2AoMIxr341RVq/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,vila velha - es,22/05/2026 às 15:15,248202851,"prezados,\nestou há semanas tentando acessar o..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-empresa-se-recusa-a-devolver-valor-antes-do-fim-do-grupo-descumprindo-a-lei_5P0wkhBokg_wYVgW/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,cambuquira - mg,22/05/2026 às 15:15,248181811,fiz a compra do consórcio quando desisti do co...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/carta-contemplada-e-dificuldade-em-realizar-a-utilizacao-informacoes-divergentes-da-central-de-atendimento_YxgyQmeLkVuONqMC/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,curitiba - pr,22/05/2026 às 15:15,248135081,"carta contemplada, processo simples de utiliza..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cobranca-indevida-de-consorcio-nao-autorizado-e-falta-de-estorno__WmExpG6LXJIsvUH/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,montividiu - go,22/05/2026 às 15:15,248133071,apareceu cobrando na minha conta corrente um c...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-imobiliario-itau-negativa-de-informacoes-sobre-contemplacoes-do-grupo_jB0Lc4b9BaGDyaJO/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,sumaré - sp,22/05/2026 às 15:15,248104069,negativa de informações sobre contemplações do...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-itau-falta-de-informacao-sobre-restricao-no-bacen-resultou-em-recusa-e-perda-financeira_-rkDHbc26O5aORpY/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,esteio - rs,12/05/2026 às 09:49,248110045,gustavo e michel me ajudaram muito até a resol...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/itau-consorcios-cobranca-abusiva-e-na-aplicacao-de-taxas-apos-cancelamento-dentro-do-prazo-contratual_rttpW__FppNH3yyG/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,santo antônio do monte - mg,12/05/2026 às 11:33,248014709,gostaria de registrar minha satisfação com o a...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cobranca-indevida-de-banco-cliente-relata-descaso-e-falta-de-solucao-para-problema-habitacional-apos-10-anos_6qlfOqkHSYxEkceX/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,rio de janeiro - rj,22/05/2026 às 15:15,247973685,quase dez anos tentando amigavelmente e nada!\...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/alerta-sobre-consorcio-itau-burocracia-excessiva-na-contemplacao-da-carta-de-credito_RpdL3YT49DyoJ93x/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,niterói - rj,22/05/2026 às 15:15,247966247,"bom dia, caros clientes do banco itaú, quero d..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cancelamento-indevido-de-consorcio-por-falta-de-contato-e-erro-cadastral_pInMy3h6x2vWuKki/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,osasco - sp,22/05/2026 às 15:15,247894185,foi realizado o cancelamento do meu consórcio ...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-promessa-de-reducao-de-parcela-no-app-nao-cumprida-gera-cobranca-excessiva-e-engano-ao-consumidor_2SacQCRG794kNZQM/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,limoeiro - pe,22/05/2026 às 15:15,247914623,realizei a aquisição de um consórcio junto a e...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/reclamacao-formal-publicidade-enganosa-e-intermediacao-em-contrato-de-consorcio-itau-pela-adm_tEz9Dpw0VrKSDMTx/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,None,06/05/2026 às 21:55,247935283,"reclamação formal prática abusiva, publicidade..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/resgate-de-3-consorcio-banco-nao-consegue-me-devolver_qIcceDrmVK7AFFMd/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,vila velha - es,22/05/2026 às 15:15,247471189,boa tarde!\nfiz uma transferência de 3 consórc...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/itau-dificuldade-de-contato-e-falta-de-retorno-sobre-consorcio-mesmo-apos-contato-com-sac-e-ouvidoria_LLH9hD8uTVxEecTS/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,sumaré - sp,22/05/2026 às 15:15,247825303,None

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cobranca-indevida-em-consorcio-de-imovel_yP7PAXMppnRXOZhX/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,belo horizonte - mg,22/05/2026 às 15:15,247876785,contratei um consórcio de imóvel junto ao ****...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-de-motocicleta-itau-informacoes-contraditorias-e-abusivas-sobre-desistencia-e-retencao-de-valores_Udvqth21iPmDhKh3/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,belo horizonte - mg,22/05/2026 às 15:15,247805471,"prezados,\nadquiri um consórcio de motocicleta..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/informacoes-sobre-consorcio-con-cnpj-baixado_r-aOTZ-3yDLSie3B/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,matozinhos - mg,22/05/2026 às 15:15,247882903,estou a dias tentando contato pelo número ****...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-itau-quitacao-de-consorcio-sem-baixa-de-gravame-no-detran_SoehnBn-tNm9RI_T/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,sobral - ce,09/05/2026 às 13:12,247827835,"prezado(a), boa tarde!\n\nesclarecemos que a a..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/reclamacao-sobre-anuencia-para-transferencia-de-imovel-em-consorcio-itau-consorcio_yR-voLWXG_0MQswV/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,curitiba - pr,22/05/2026 às 15:15,247808049,eu e meu esposo temos um consorcio que ja foi ...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cobra-taxa-de-avaliacao-indevida-para-veiculo-zero-km_QqeLv2A4Zh14KI7e/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,são paulo - sp,22/05/2026 às 15:15,247800071,o ***** me comprou uma taxa de avaliação do ve...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-valor-de-resgate-inferior-ao-pago-solicito-investigacao_H58_LoAjzaFKOHQT/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,uruará - pa,22/05/2026 às 15:15,247762409,em 2021 entrei em um consórcio paguei a primei...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/erro-na-sequencia-registral-faturamento-de-veiculo-impossivel_Oe99DV8Kpuo78Igy/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,anápolis - go,05/05/2026 às 12:40,247760761,sou titular de duas cotas de consórcio itaú (*...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cobranca-indevida-apos-pagamento-e-dificuldade-de-resolucao-com-o-banco_KwMSaI5e_YU6sgsh/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,santo andré - sp,05/05/2026 às 09:25,246443751,o banco está me cobrando uma parcela do mês de...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cobranca-de-multa-e-taxa-administrativa-indevida-em-cancelamento-de-consorcio-imobiliario-por-venda-mal-feita_lz1P35tI2yAnYRSG/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,belo horizonte - mg,22/05/2026 às 15:15,247697127,em agosto de 2025 o gerente do itaú uniclass o...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/dificuldade-em-obter-informe-de-rendimento-para-imposto-de-renda-apos-promessa-de-envio-por-e-mail-nao-cumprida-e-falhas-no-atendimento-telefonico_QOSS-HcB8X-_f3w9/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,rolândia - pr,05/05/2026 às 10:37,247683889,"olá, matheus.\n\nesperamos que esteja bem :)\n..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/banco-retem-r-479-mil-apos-falecimento-descumpre-prazos-do-banco-central-e-ignora-familia_8O_JnD-Rln6ljVba/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,cuiabá - mt,22/05/2026 às 15:15,247673413,venho por meio desta registrar minha indignaçã...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/vendedor-promete-contemplacao-e-empresa-nao-reconhece-ma-conduta-mesmo-com-provas_SaQDg5-IJWT48QVl/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,mucuri - ba,04/05/2026 às 16:14,247670249,"é tão desgastante isso tudo ,tenho vídeos da t..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/dificuldade-em-encerrar-conta-pj-e-migrar-debitos-apos-mau-atendimento-no-banco-itau_gDMlv1P2uggsFWzL/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,aracaju - se,22/05/2026 às 15:15,246787435,"eu era cliente pj , sendo que a conta é virtua..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/problemas-com-a-transferencia-de-documento-de-veiculo-apos-quitacao-de-consorcio-itau_mLu8L5vmajMOKVLi/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,lagoa santa - mg,22/05/2026 às 15:15,247583839,"meu nome é luciene, tenho um veículo do consór..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/demora-na-substituicao-de-garantia-e-baixa-de-gravame-com-prazos-excedidos-e-falta-de-solucao-pela-central-de-atendimento_M7p1VthhI0xQ2PBR/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,uberlândia - mg,22/05/2026 às 15:15,247440081,estou fazendo um processo de substituição de g...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/dificuldade-na-reativacao-de-consorcio-informacoes-inconsistentes-e-desculpas-diarias-dos-atendentes-bancarios_Z20hK6tstS2Mzs6l/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,guarulhos - sp,22/05/2026 às 15:15,247391669,estou tentando a reativação de um consórcio co...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-contemplado-mas-banco-alega-nao-constar-no-sistema-e-nega-deposito_yMDxSTbbFkg6ioj2/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,None,22/05/2026 às 15:15,247538743,recebi um comunicado através do app do banco i...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/restricao-de-alienacao-fiduciaria-indevida-no-detran-apos-quitacao-de-divida-com-o-itau_apVUD1cDOlAWg4UI/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,salvador - ba,07/05/2026 às 17:53,247510839,"prezado(a), boa tarde!\n\nesclarecemos que a a..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/demora-na-conclusao-da-substituicao-de-garantia-e-baixa-de-gravame_CYx1uT4m3d5BVMzY/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,uberlândia - mg,05/05/2026 às 15:00,247439859,"prezado,\n\nprimeiramente, agradecemos a oport..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/problemas-na-venda-de-imovel-via-consorcio-itau-falta-de-comunicacao-e-atrasos-no-processo-de-interveniente-quitante_br_W6KDrHO8f1rbl/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,porto ferreira - sp,22/05/2026 às 15:15,247417511,"desde o início de abril de 2026, estou tentand..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-itau-informacao-de-contemplacao-incorreta-no-aplicativo-gera-insatisfacao_ynmj-wq8SBCXFasE/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,são paulo - sp,22/05/2026 às 15:15,247411491,"cancelei meu consórcio do itaú, 3 meses atrás,..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/falha-na-comunicacao-de-contemplacao-de-consorcio-e-recusa-de-aprovacao-de-credito-para-aquisicao-de-veiculo_i9VFE1q203JIZrlZ/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,belo horizonte - mg,22/05/2026 às 15:15,247351507,aderi ao grupo de consorcio de veículo em abri...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/insatisfacao-com-consorcio-e-atendimento-no-banco-itau_NQY2u3eXe_46FWbU/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,patos de minas - mg,22/05/2026 às 15:15,247211625,"tenho uma conta empresarial no banco itaú , se..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/itau-consorcio-erro-no-nome-impede-transferencia-de-veiculo-no-detran-rj_9MGtFSriVg1A6RjW/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,rio das ostras - rj,22/05/2026 às 15:15,247325593,"em 12/02/2026, solicitei ao itaú consórcio a c..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/retencao-abusiva-de-valores-pagos-no-consorcio-itau-apos-cancelamento_QOPL1OsaGMYqzA62/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,barcarena - pa,22/05/2026 às 15:15,247292067,paguei uma parcela de consórcio e cancelei. lo...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-itau-realizou-o-cancelamento-de-cota-sem-aviso-previo-ao-consorciado_NhP11FlXiK1xLXt0/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,salvador - ba,22/05/2026 às 15:15,247268727,venho por meio desta registrar uma reclamação ...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/insatisfacao-com-o-atendimento-do-itau-personnalite-na-substituicao-de-garantia-de-consorcio-com-taxas-ja-debitadas-e-falta-de-retorno_uX0aynF2pfM662Wx/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,fortaleza - ce,22/05/2026 às 15:15,247159581,"sou cliente do itaú há mais de 20 anos, segmen..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/solicitacao-de-transferencia-de-cota-mediante-procuracao-para-nao-correntista_3rZjziCaqrThoFFB/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,porto velho - ro,12/05/2026 às 16:56,247197969,"olá lucas, boa tarde!\n\nidentificamos em sist..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/contratacao-de-consorcio-com-informacoes-enganosas-e-cobranca-indevida-itau-unibanco_MCJGHy38Dx49BMNh/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,contagem - mg,28/04/2026 às 14:26,246646387,venho por meio desta registrar reclamação cont...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/venda-casada-ao-abrir-conta-pj-contratacao-indevida-na-pessoa-fisica-e-prejuizo-financeiro_fOoE8QgKFjE7lcXz/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,balneário camboriú - sc,22/05/2026 às 15:15,245840963,título: venda casada ao abrir conta pj contrat...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/itau-consorcio-quer-reter-mais-de-50-do-meu-dinheiro-sem-transparencia_s-B6f9gb1LKlFz-E/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,barra dos coqueiros - se,22/05/2026 às 15:15,247151471,protocolo de atendimento: ***** tenho um consó...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cobranca-indevida-e-informacoes-enganosas-sobre-consorcio-imobiliario-itau_UIExllOuIgIIF4QX/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,são paulo - sp,22/05/2026 às 15:15,247101713,"no dia 09 de março de 2026, fiz contato via wh..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/itau-consorcio-cancelamento-de-transferencia-de-cotas-sem-justificativa-plausivel-apos-meses-de-processo-e-cumprimento-de-etapas_5a5czd47A4LJLtdT/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,santo andré - sp,22/05/2026 às 16:39,247143729,"olá, prezado(a), boa tarde.\n\nesperamos que e..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/solicitacao-de-gravacao-de-ligacao-de-consorcio-divergencia-de-informacoes-sobre-lance-embutido__5XAbiaNa9VDiZhk/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,são paulo - sp,22/05/2026 às 15:15,247111683,None

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/descumprimento-contratual-e-prejuizos-financeiros-pelo-banco-itau-e-protech-consorcios-no-fracionamento-de-carta-de-credito_iUMSola_CA7a7HFt/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,santo andré - sp,21/05/2026 às 14:30,247100529,"prezado,\n\nprimeiramente, agradecemos a oport..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cobranca-alterada-sem-aviso-negativacao-indevida-mesmo-com-saldo-disponivel_e2aDRT8K-sBRVRBd/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,são lourenço do oeste - sc,15/05/2026 às 08:55,247049473,"olá, douglas.\n\nesperamos que esteja bem :)\n..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/solicitacao-de-ressarcimento-de-valores-faltantes-em-consorcio_bdt5Y5ehjqFcCuKO/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,boituva - sp,22/05/2026 às 15:15,247060411,em 2013 adquiri um consorcio grupo ***** quota...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/propaganda-enganosa-e-falta-de-transparencia-em-cota-de-consorcio-com-promessa-de-devolucao-imediata_AAntVyeZfZBR-rUn/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,não respondida,são paulo - sp,22/05/2026 às 15:15,247006569,"cota *****, grupo *****, promessa de devolução..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/impossibilidade-de-simular-consorcio-pelo-aplicativo-ha-um-mes_IBNQhTbbUMlnD515/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,brasília - df,22/05/2026 às 13:16,246969413,"olá, boa tarde!\n\nesclarecemos que, a concess..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-dificuldade-na-compra-de-moto-contemplada-com-perda-de-desconto-devido-a-falhas-no-sistema-e-mau-atendimento_0G5Xnqxu_PVYVqc0/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,poções - ba,11/05/2026 às 20:43,246944835,o problema no atendimento foi que fiz tudo que...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cancelamento-de-consorcio-e-estorno-de-dinheiro-nao-realizado-apos-uma-semana_FRFRSWUe7asUE0pd/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,são paulo - sp,30/04/2026 às 09:07,246926235,"prezado,\n\nprimeiramente, agradecemos a oport..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-itau-se-recusa-a-emitir-carta-de-contemplacao-gerando-risco-de-multa-e-prejuizo-financeiro-para-cliente_ybRVMThq52aTb_5C/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,são paulo - sp,"olá, henrique.\n\nrecebemos a sua manifestação...",246882999,após a contemplação por sorteio no consórcio i...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/veiculo-quitado-em-consorcio-pelo-itau-continua-alienado-no-detran-es-e-canais-de-atendimento-nao-resolvem_rPvmClp8OxEyxpNT/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,colatina - es,22/05/2026 às 13:10,246865193,"prezado,\n\n\nprimeiramente, agradecemos a opo..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/imovel-itau-consorcios-demora-na-devolucao-de-valores-pagos-de-consorcio-imobiliario-cancelado-em-2011_705c0qBdpKAAaGRB/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,None,21/05/2026 às 14:32,246866171,"olá elton, boa tarde!\n\nesclarecemos que a de..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-itau-erro-em-agencia-atraso-na-liberacao-de-credito-apos-contemplacao_LX0n-US4uSBhm7_1/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,teresópolis - rj,22/05/2026 às 08:28,246844587,"prezado,\n\nprimeiramente, agradecemos a oport..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/liberacao-indevida-de-credito-de-consorcio-e-inclusao-irregular-de-gravame-pelo-banco-itau_JIAvCSLhHL_jHZfD/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,None,22/05/2026 às 17:47,246789021,"prezado,\n\nprimeiramente, agradecemos a oport..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/itau-consorcio-dificuldade-na-liberacao-de-venda-de-cartas-de-credito-mesmo-com-comprador-idoneo_ed1xE3-Y8ekwEhtc/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,são paulo - sp,22/05/2026 às 13:05,246793463,"prezado,\n\nprimeiramente, agradecemos a oport..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cliente-solicita-estorno-de-consorcio-imobiliario-nao-contratado-e-nao-reconhecido_vSgdHh04TDwztIfm/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,santo andré - sp,21/05/2026 às 15:17,246773085,"olá manuel, boa tarde!\n\nesclarecemos que a d..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/banco-itau-falha-na-prestacao-de-servico-e-demora-na-analise-de-solicitacao-de-consorcio_MT0QaSbPUce96Voq/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,são paulo - sp,22/05/2026 às 08:27,246767561,"prezado cliente, evelyn!\n\ninicialmente, temo..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/impossibilidade-de-obter-extrato-de-cota-de-consorcio-e-senha-bloqueada-no-app-do-banco_gZHpYqXQRqCHSYO6/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,são paulo - sp,22/05/2026 às 18:44,246742611,"olá luiz, esperamos que esteja bem :)\n\nescla..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/solicitacao-de-devolucao-de-valor-pago-em-consorcio-itau-apos-inadimplencia_IZ0h3ZWYEu7fqb3C/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,salvador - ba,22/05/2026 às 13:02,246712923,"oi, esperamos que esteja bem.\n\nesclarecemos ..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/demora-excessiva-e-falta-de-retorno-em-processos-de-transferencia-de-cotas-de-consorcio-junto-ao-itau_aTIpL3mmqwzRCXnV/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,santo andré - sp,18/05/2026 às 09:24,246686005,"prezado,\n\nprimeiramente, agradecemos a oport..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/banco-itau-retendo-74-do-valor-pago-em-consorcio-de-veiculo-apos-solicitacao-de-cancelamento_CU9Y7h_z467-WiCt/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,belo horizonte - mg,21/05/2026 às 09:12,246685077,"oi vinicius, esperamos que esteja bem :)\n\nes..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cobranca-indevida-de-valor-para-compra-de-casa-sem-notificacao-e-dificuldade-de-estorno_WJFxJ0AMiE9xtUqV/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,cachoeiras de macacu - rj,30/04/2026 às 20:07,246630677,"olá joão, boa tarde!\n\nrecebemos sua manifest..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/nao-consigo-administrar-o-consorcio-pelo-aplicativo_Hgm34GEqgU2BK7j-/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,niterói - rj,21/05/2026 às 13:39,246594603,"prezado, agradecemos o seu contato.\n\no itaú ..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/falta-de-analise-e-retorno-adequado-as-solicitacoes-sobre-consorcio_OsWEgCW4lrZ1CaoF/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,sumaré - sp,"olá marcos, boa tarde!\n\napós a finalização d...",246626695,falta de análise e retorno adequado as solicit...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/itau-unibanco-falta-de-repasse-de-dinheiro-de-consorcio-cancelado-e-contemplado-por-sorteio_iUKBXa9CWpsjZfUQ/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,jussara - go,04/05/2026 às 13:21,246604687,"quero elogiar o atendimento do itaú, especialm..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/demora-na-baixa-do-gravame-de-consorcio-quitado-pelo-itau-consorcio-impedindo-a-venda-do-veiculo_QPdaqEH8fhusptXq/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,brasília - df,20/05/2026 às 09:23,246585077,"olá, milena!\n\nesperamos que esteja bem:)\n\n..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/taxa-administrativa-abusiva-em-consorcio-de-veiculo-e-restricao-de-idade-do-bem_X1uHLQtjluiGQvMl/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,são paulo - sp,19/05/2026 às 08:58,246549817,"olá, boa tarde!\n\ntodo consórcio possuí restr..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/dificuldade-na-utilizacao-do-fgts-para-abatimento-de-parcela-de-consorcio-itau_Hm554wCdtR0iGCMd/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,rio de janeiro - rj,"olá carlos, boa noite!\n\nsentimos muito pelo ...",246532031,estou registrando uma reclamação referente ao ...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/imovel-com-defeito-cobranca-indevida-apos-quitacao-de-consorcio-e-atraso-na-baixa-do-gravame_8KvzICpUZj-oU7e_/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,recife - pe,20/04/2026 às 17:39,246525549,olá vinicius.\n\nesclarecemos que a alienação ...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/demora-na-baixa-de-gravame-de-consorcio-quitado-de-moto-apreendida_hnUKsZcocEFE3YbY/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,None,28/04/2026 às 08:00,246515431,"prezado,\n\nprimeiramente, agradecemos a oport..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/solicitacao-de-esclarecimentos-sobre-cobranca-de-tarifa-de-avaliacao-de-bem-sem-comprovacao-de-servico-prestado_LOYcrjB0k07Sey2K/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,barueri - sp,19/05/2026 às 08:50,246511423,"prezado josé, bom dia!\n\ngostaríamos de escla..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-nao-cobre-moto-off-road-apesar-de-contemplacao-por-lance-cliente-se-sente-enganado_RhoHScB6t90Gzece/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,valinhos - sp,14/05/2026 às 16:36,246510723,"olá, boa tarde!\n\ntodo consórcio possuí restr..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/erro-no-sistema-impede-faturamento-de-veiculo-contemplado-em-carta-de-credito-causando-perda-de-negociacao-e-insatisfacao-do-cliente_k-C_Qs3qJKpja-X8/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,goiânia - go,19/05/2026 às 09:58,246496009,"prezado cliente,\n\ninicialmente, temos a escl..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-itau-demora-na-devolucao-de-valores-apos-cancelamento-ha-mais-de-5-anos_bPxhFTkbFdfP29TF/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,belo horizonte - mg,15/05/2026 às 15:13,246451163,"david, boa tarde!\n\nesclarecemos que a devolu..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-itau-cobranca-abusiva-e-impossibilidade-de-ressarcimento-antecipado_Vu_XJi31Wyz9E3YV/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,salvador - ba,15/05/2026 às 15:58,246350671,"olá tatiane, boa tarde!\n\nesclarecemos que a ..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-promessa-de-contemplacao-nao-cumprida-e-cobranca-abusiva-na-cancelamento_9qAl5UuNrx2IH_Vr/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,balneário piçarras - sc,15/05/2026 às 09:58,246344245,"oi maikon, esperamos que esteja bem :)\n\nescl..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/propaganda-enganosa-consorcio-imobiliario-itau-contemplacao-prometida-nao-realizada-e-valores-retidos_H6HQgaN-lhoLuO_f/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,sumaré - sp,15/05/2026 às 09:46,246338361,"olá, bom dia!\n\nesperamos que esteja bem :)\n..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cota-de-consorcio-necessidade-de-verificacao-e-ativacao-urgente_-M-RgRr_BAXAPtBL/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,cuiabá - mt,17/04/2026 às 15:13,246254725,ok. obrigado pelo rápido retorno e resolução.\...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-empresarial-sem-informacoes-sobre-status-ou-sorteio-apos-anos-de-pagamento_kp3lxYldH6IWWepM/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,nova iguaçu - rj,15/05/2026 às 09:46,246251529,oi alyson esperamos que esteja bem.\n\nesclare...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-com-promessa-de-contemplacao-rapida-e-nao-cumprimento-das-expectativas-vendedor-induz-ao-pagamento-antecipado-sem-garantia_Y7_mEmehBpTtwSJY/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,mucuri - ba,15/05/2026 às 19:38,246204209,e outra nunca falei com vendedor que daria sem...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-impossibilidade-de-acesso-a-assembleias-e-informacoes-de-lances-pelo-app-e-portal-documento-em-branco-enviado_q2mwqw1BkY3CLVnO/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,araguari - mg,04/05/2026 às 12:41,246168077,"prezado,\n\nprimeiramente, agradecemos a oport..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/banco-cobra-juros-abusivos-em-carta-de-credito-e-impede-cancelamento_LQvp1AiqOhVXljqu/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,cristalina - go,14/05/2026 às 13:45,246072749,"oi alex, esperamos que esteja bem :) esclarece..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/itau-nao-deu-baixa-em-consorcio-de-carro-quitado-impedindo-licenciamento-e-gerando-transtornos-ao-cliente_dIcVbFeOAHYZTZJC/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,florianópolis - sc,14/05/2026 às 11:53,246135311,"prezado cliente,\n\n\ninicialmente, temos a es..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/reclamacao-sobre-propaganda-enganosa-e-dificuldade-em-recuperar-dinheiro-de-consorcio-cancelado-com-o-itau_pPJCdyrS1A2STSZC/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,ipatinga - mg,15/05/2026 às 00:22,246133199,eu quero meu dinheiro de volta... vou colocar ...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/nunca-comprem-um-consorcio-do-itau-informacao-enganosa-sobre-contemplacao-por-meio-do-lance_-XSOOs_w4H_iSdM-/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,são paulo - sp,16/05/2026 às 10:57,246127837,"olá eliana,\n\nidentificamos que as questões a..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/venda-inadequada-do-produto-falta-de-transparencia-informacao-insuficiente-sobre-grupos_0nr8oaH94Y6_GUso/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,goiânia - go,14/05/2026 às 21:24,246117717,"olá, boa tarde!\n\nesperamos que esteja bem :)..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cliente-solicita-reembolso-de-valor-pago-em-consorcio-imobiliario-apos-sugestao-de-gerente_RoFhxuV5RcHAxD91/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,santa luzia - mg,14/05/2026 às 11:04,246091495,"olá,\n\nesperamos que esteja bem.\n\nesclarece..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/banco-itau-nao-baixa-gravame-apos-quitacao-e-esta-causando-risco-de-acao-judicial-contra-mim_-GXIU1KKX0IoiuHR/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,são paulo - sp,13/05/2026 às 13:50,246074013,"olá, raimundo!\n\nesclarecemos que a alienação..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/itau-se-recusa-a-emitir-carta-de-quitacao-de-consorcio-de-veiculo-furtado-impedindo-o-recebimento-do-seguro_WZmDUxFpF5O7N9rD/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,belo horizonte - mg,13/05/2026 às 13:54,246025555,"olá, victor.\n\nesperamos que esteja bem.\n\na..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/impossibilidade-de-emissao-de-comprovante-de-pagamento-de-taxa-de-contemplacao-de-consorcio_WBxtmyDwOMBAs1Ha/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,taubaté - sp,13/05/2026 às 19:42,246025111,"olá, diana, boa tarde!\n\nagradecemos por entr..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-itau-falta-de-baixa-de-gravame-apos-quitacao-do-veiculo_S3Oca0O14IYp6HsM/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,porto velho - ro,22/05/2026 às 13:13,246012975,[editado pelo reclame aqui]. falta de respeito...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-de-reforma-banco-itau-pessimo-atendimento-e-falta-de-clareza-sobre-contemplacao-de-lance_nwNEuYC4-haS-vYd/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,manaus - am,15/05/2026 às 15:36,246003593,"as respostas são muito evasivas, uma vez que n..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/solicitacao-de-demonstrativo-de-evolucao-da-divida-contratos-n-0095442-e-0095525_zd1_Ep9D5ZclJGJU/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,campinas - sp,13/05/2026 às 11:53,245985245,"prezado cliente,\n\ninicialmente, temos a escl..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/solicitacao-de-transferencia-de-cota-com-procuracao-para-nao-correntista_k-tR4sgH96EEZOdI/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,porto velho - ro,12/05/2026 às 16:56,245929467,"olá lucas, boa tarde!\n\nidentificamos em sist..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/propaganda-enganosa-em-consorcio-itau-cliente-exige-devolucao-imediata-de-valores-pagos-apos-ser-induzido-ao-erro_VihsLicGCKOBbHOU/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,nova iguaçu - rj,12/05/2026 às 14:15,245827203,não considero justo que o itaú permaneça com u...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/solicitacao-de-analise-de-distrato-administrativo-e-apuracao-de-valores-a-restituir-em-consorcio-de-veiculos-leves_P0JrKkRU50JI2ple/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,sobral - ce,12/05/2026 às 16:19,245886773,"olá eduardo, esperamos que esteja bem :)\n\nes..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/compra-de-veiculos-com-pneus-remoldados-nao-informados-e-promessa-de-isencao-de-ipva-nao-cumprida_zVCYLl2PEwgXYl9s/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,luziânia - go,12/05/2026 às 11:04,245878121,"prezado,\n\nprimeiramente, agradecemos a oport..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cancelamento-de-consorcio-sem-notificacao-previa-apos-atraso-de-pagamento-por-falha-na-entrega-de-boletos_Nn2SbsCXftIx7O7u/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,campinas - sp,08/05/2026 às 19:13,245734323,"olá prezado(a)\n\nsobre sua manifestação, cabe..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cobranca-indevida-de-taxas-de-administracao-e-avaliacao-em-consorcio-itau-apos-contemplacao_6S7kTAfWYCAq2EjC/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,rio de janeiro - rj,08/05/2026 às 10:58,245663187,"prezada cliente, marcia!\n\ninicialmente, temo..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/venda-a-qualquer-preco-zero-transparencia-e-preocupacao-em-suprir-a-real-necessidade-do-cliente_2J5HhHrQ2_AYWYBf/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,são paulo - sp,08/05/2026 às 20:11,245518301,não concordo com a resposta. quem pediu uma si...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/impossibilidade-de-resgate-de-valores-de-consorcio-e-cobranca-indevida-pelo-itau_LY2bBytU5Ltxr8yb/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,cidade ocidental - go,08/05/2026 às 09:37,245565199,"olá filipe, bom dia!\n\nesclarecemos que a dev..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/do-falso-consorcio-idoso-se-sente-e-nao-consegue-sacar-valor-de-consorcio-contemplado-apesar-de-promessa-de-saque-feita-em-oferta-inicial_bLo3-3ZdJZyCxtCl/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,None,07/05/2026 às 13:34,245549377,"olá, boa tarde!\n\nesclarecemos que a devoluçã..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-contemplado-com-reajuste-indevido-de-parcelas-e-dificuldade-de-contato-com-o-banco-itau_EuDPqyyC3QWY_J4o/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,vargem grande paulista - sp,07/05/2026 às 12:48,245548025,"péssimo atendimento, me sinto [editado pelo re..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/transferencia-indevida-de-cota-de-consorcio-para-empresa-sem-consentimento-do-titular_ERyEzFSJV6hqmFcQ/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,valparaíso de goiás - go,07/05/2026 às 13:27,245545617,"prezado,\n\nprimeiramente, agradecemos a oport..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/aguardando-devolucao-de-valor-alega-manipulacao-em-sorteio-e-tentativa-de-engano_sZj7Swo9gMEBwDNr/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,salvador - ba,11/05/2026 às 08:24,245493695,"oi, esperamos que esteja bem.\n\nesclarecemos ..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/imovel-adquirido-por-consorcio-alaga-e-destroi-bens-em-menos-de-dois-meses-banco-ciente-do-problema-ha-mais-de-dez-anos_Hb67m-eVVZCCQx_c/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,rio de janeiro - rj,12/05/2026 às 09:33,245471087,"mas não se trata de evento posterior, se trata..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/propaganda-enganosa-em-consorcio-imobiliario-itau-promessa-de-contemplacao-em-6-meses-com-40-de-lance-nao-cumprida_9xSr8xlqAWsLS7JU/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,sumaré - sp,06/05/2026 às 10:22,245381363,"olá, bom dia!\n\nesperamos que esteja bem :)\n..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cobranca-indevida-e-exclusao-injusta-de-cota-de-consorcio-por-falha-no-debito-automatico-do-itau_-u6dVnGncYY2n353/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,rio de janeiro - rj,21/05/2026 às 21:06,245419813,que linha de crédito para consórcio ? eu quero...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/atraso-na-liberacao-de-pagamento-da-administradora-imovel_PTZJZEK7k9no0gA2/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,curitiba - pr,16/04/2026 às 02:09,245414147,"olá, wellington.\n\nesperamos que esteja bem :..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cobranca-indevida-apos-transferencia-de-consorcio-e-solicitacao-de-estorno_Q9sNKsgur4OvS-Zy/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,belo horizonte - mg,06/05/2026 às 10:30,245388615,"eu sou detentora da conta sim, resposta sem ne..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cliente-contesta-retencao-de-valores-e-multa-em-consorcio-imobiliario-apos-exclusao-de-cota_8SFQ_8ksjKM40LvU/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,belo horizonte - mg,06/05/2026 às 09:41,245369201,"oi humberto, esperamos que esteja bem.\n\nescl..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-feito-sem-autorizacao-pelo-itau_vGBaMQ8Er0J_6aow/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,rio de janeiro - rj,06/05/2026 às 11:13,245358455,"olá rosalia, bom dia!\n\nesperamos que esteja ..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/aguardando-contato-do-consorcio-itau-para-resolucao-de-faturamento-de-veiculo-pcd_p68BaTWrNFjSlI3z/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,feira de santana - ba,19/04/2026 às 11:15,245256909,profissional thiego que me atendeu foi de uma ...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/reprovacao-abusiva-apos-aprovacao-e-pagamento-de-taxas-de-consorcio-contemplado-itau-administradora-de-consorcios_wU47e1xPKzwZ6db_/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,rio de janeiro - rj,30/04/2026 às 19:53,245239381,"olá eric, boa noite!\n\nesclarecemos que, a co..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cobranca-indevida-de-taxas-de-consorcio-sem-comprovante-de-pagamento-e-impossibilidade-de-rastreio-interno_yCTuUMisjvpy7Gy6/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,rio de janeiro - rj,30/04/2026 às 18:29,245145995,"olá, eduarda. esperamos que esteja bem!\n\nem ..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/contratacao-de-consorcio-e-seguro-de-vida-induzida-sem-contemplacao-de-credito-e-sem-devolucao-do-valor-pago-apos-2-anos_CmxQDQjlCi_X1up1/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,manaus - am,01/05/2026 às 04:46,245131099,entendo suas [editado pelo reclame aqui] norma...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-itau-falta-de-informacao-sobre-restricao-no-bacen-resultou-em-processo-enganoso-e-perda-financeira_ZpsSKS1cy9jAxlko/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,esteio - rs,03/05/2026 às 13:03,245031157,"olá, bom dia!\n\nesclarecemos que, a concessão..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/demora-no-ressarcimento-de-consorcio-cancelado-pelo-banco-itau-apos-mais-de-3-anos_1E8OgoN328hENSJV/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,montes claros - mg,30/04/2026 às 20:59,245085121,"contemplação ou não do consórcio itaú, o valor..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/empresa-de-consorcio-nao-devolve-valor-pago-apos-cancelamento-ha-mais-de-3-anos-e-nao-responde-contatos_FYqT8TAnyNRuz0nF/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,rianápolis - go,03/05/2026 às 17:17,245049383,"resolveu ó problema parcial devolve só r$ 530,..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/contrato-de-consorcio-com-beneficiario-em-nome-errado-cobranca-indevida-e-quebra-de-confianca_TjVyPOyytgHeVe1s/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,são paulo - sp,02/05/2026 às 09:43,245045855,"prezado cliente,\n\ninicialmente, temos a escl..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/promessa-de-contemplacao-em-consorcio-nao-cumprida-resultando-em-perda-de-imovel-e-dinheiro-retido_oMMQ3YfYdj2u6V9-/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,piracicaba - sp,30/04/2026 às 20:55,244998297,"no fim o cliente só perde, as duas parcelas pa..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cobranca-abusiva-de-taxa-de-avaliacao-em-consorcio-de-veiculo-0km_Mu2G4DXf8WWEjpK1/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,salvador - ba,30/04/2026 às 08:57,245038487,"olá, se você é cliente do consórcio itaú e che..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-imoveis-itau-dificuldade-na-transferencia-de-titularidade-apos-falecimento-da-titular-e-risco-de-retomada-do-imovel_e6F969Q4y5cyfB6r/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,rio de janeiro - rj,02/05/2026 às 09:45,244970515,"prezado cliente,\n\ninicialmente, temos a escl..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-itau-avalia-veiculo-abaixo-do-valor-de-mercado-impedindo-a-compra-apos-contemplacao_TlO5Jvs5H6LDjIm4/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,None,28/04/2026 às 14:51,244969615,"olá pedro, boa tarde!\n\nesclarecemos que, a c..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-itau-avalia-incorretamente-veiculo-contemplado-impedindo-a-compra-planejada-e-desrespeitando-o-cliente_ljeSPIPGnQrl3-Fi/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,None,29/04/2026 às 19:01,244970965,"olá pedro.\n\nesclarecemos que, a concessão de..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/contratacao-indevida-de-consorcio-e-cobranca-recorrente-sem-consentimento-do-cliente-idoso-e-analfabeto_R9x9lnRnB6tQju_B/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,macapá - ap,08/05/2026 às 20:24,244848125,"olá pedro, boa noite!\n\nesclarecemos que a de..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/retencao-abusiva-de-valores-em-consorcio-imobiliario-e-solicitacao-de-devolucao-antecipada_6fdMGkjCAhSeZpnk/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,são paulo - sp,30/04/2026 às 08:28,244887169,"oi soraia, esperamos que esteja bem :)\n\nescl..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/atraso-no-processo-de-transferencia-de-cota-com-procurador-e-falta-de-retorno-dos-atendentes_TYicQFrsCYkEBWhw/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,porto velho - ro,22/04/2026 às 11:10,244790063,queria parabenizar aqui o atendente gustavo qu...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/itau-unibanco-atraso-e-erro-na-emissao-de-contrato-de-substituicao-de-bem-em-consorcio-gera-risco-de-perda-de-negociacao-de-carro-novo_sT7YaaYMsCgAGf7Z/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,santo andré - sp,30/04/2026 às 19:27,244784327,"olá, bom dia!\n\nesperamos que esteja bem :)\n..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/falta-de-transparencia-e-informacoes-sobre-valores-a-receber-de-consorcio-cancelado_cyOUJHlfONhuIPac/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,são paulo - sp,29/04/2026 às 15:13,244619701,"olá nayara, boa tarde!\n\nesclarecemos que a d..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-itau-inducao-ao-erro-falta-de-transparencia-e-proposta-de-devolucao-abusiva-de-valores_r6zjKnnDX1kYaSp9/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,são paulo - sp,29/04/2026 às 08:52,244690425,"olá, rafael.\n\nesperamos que esteja bem!\n\nc..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/falha-na-prestacao-de-servico-itau-consorcio-atraso-na-substituicao-de-veiculo_H_gc9j_FRMw84mG9/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,sao paulo - sp,25/04/2026 às 10:57,244549767,"prezado,\n\nprimeiramente, agradecemos a oport..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/itau-consorcio-falha-na-transparencia-e-nao-fornecimento-de-gravacoes-telefonicas_G1OM7VO-RqDyTpYD/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,são bernardo do campo - sp,"prezados,\n\na resposta apresentada pela insti...",244548395,"olá freedy, boa noite!\n\nem atenção ao seu pe..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-itau-promessa-de-contemplacao-em-3-meses-nao-cumprida-valor-retido-e-devolucao-apenas-em-2030_mXw50NXN4gZucCyT/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,são paulo - sp,27/04/2026 às 15:02,244536147,pq eles em nenhum momento tentou resolver a qu...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/demora-na-liberacao-de-credito-de-consorcio-para-compra-de-veiculo-sem-solucao-apos-varios-protocolos-e-prejuizo-financeiro_UI8eZrMRhoKyiyc4/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,uberlândia - mg,25/04/2026 às 10:53,244494901,"olá, boa tarde!\n\nesperamos que esteja bem :)..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-itau-lance-e-contemplacao-divergencia-de-valor-e-reajuste-da-carta_82rSyNfqhjn4pRey/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,são paulo - sp,"prezada sra. maria, boa noite!\n\nem resposta ...",244486831,"ola .\nmeu nome é *****, no mês de março efetu..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cobranca-de-juros-indevidos-e-falha-no-debito-automatico-de-consorcio-imobiliario_Eg7K1QtKzf-pf_MF/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,santo andré - sp,26/04/2026 às 10:32,244447959,o atendimento só foi eficiente qnd abri a recl...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/recusa-em-filtro-interno-impede-transferencia-de-consorcio-mesmo-com-pagamentos-em-dia_oPhlpZ7Inn4JhIbB/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,pedro canário - es,25/04/2026 às 10:48,244458823,"olá, prezado(a), bom dia.\n\nesperamos que est..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/descaso-e-falta-de-solucao-apos-fechamento-de-contrato-com-consorcio-itau_FGXAc39VFQo_q2VK/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,são joão del rei - mg,24/04/2026 às 18:05,244402795,"prezado cliente, thiene!\n\ninicialmente, temo..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-valor-de-quitacao-diverge-entre-aplicativo-e-sac-impedindo-geracao-de-boleto_-KmqLw7rfFsx4YT6/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,jaboatão dos guararapes - pe,25/04/2026 às 11:00,244398343,"olá, cleberson,\n\nagradecemos o seu contato e..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/itau-cobra-taxa-de-administracao-abusiva-acima-da-prevista-em-contrato-em-consorcio-imobiliario-e-se-recusa-a-restituir-o-valor_bBbeSzFM3x1O-_xd/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,santo andré - sp,24/04/2026 às 18:10,244327531,"olá marcus, boa noite!\n\nesclarecemos que a d..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-itau-taxas-absurdas-atendimento-confuso-e-problemas-na-transferencia-de-veiculo_QXnw8SkKDeq9cy7p/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,são paulo - sp,27/04/2026 às 09:26,244342911,"péssimo, atendentes atrapalhados, cada ligação..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/falha-na-liberacao-de-carta-de-credito-contemplada-para-compra-de-veiculo-seminovo-pelo-consorcio-itau_uG_Ldo2WbRPQjhma/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,None,None,None,este site utiliza um serviço de segurança para...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/abriram-consorcio-no-meu-nome-sem-eu-saber_1R3i6tBPJOKJxWlI/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,None,None,None,este site utiliza um serviço de segurança para...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/retencao-indevida-de-valores-de-consorcio-contemplado-e-falha-na-prestacao-do-servico-pelo-banco-itau_t-G_rJZIUeyyQR61/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,None,None,None,este site utiliza um serviço de segurança para...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-quitado-com-alienacao-ativa-indevida-no-detran-impede-venda-de-veiculo_wGNl_9Dh3MmAd5XP/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,None,None,None,este site utiliza um serviço de segurança para...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/demora-na-resolucao-de-protocolo-e-envio-incorreto-de-termo-de-transferencia-de-cotas-de-consorcio_xMUdPbBRyIAG6fTL/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,None,None,None,este site utiliza um serviço de segurança para...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cobranca-indevida-no-consorcio-repasse-de-custo-de-registro-e-avaliacao-de-veiculo-sem-transparencia_OhckmuQe72a_93VE/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,None,None,None,este site utiliza um serviço de segurança para...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/demora-na-substituicao-de-garantia-de-consorcio-e-descaso-do-banco-itau-com-o-cliente_46NCcHbvT7rgkIRy/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,None,None,None,este site utiliza um serviço de segurança para...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/impossibilidade-de-contato-com-a-central-de-atendimento-para-reativacao-de-consorcio-cancelado_RCv1erp1ahv0cd9o/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,None,None,None,este site utiliza um serviço de segurança para...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-impossibilidade-de-reativar-cota-com-valor-menor-e-cobranca-de-juros-abusivos_7uKT1tphY5mn4RTd/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,None,None,None,este site utiliza um serviço de segurança para...

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/reativacao-de-cota-imobiliaria-dificuldade-no-atendimento-e-falta-de-informacao-clara_0txjsb4OuPfOYtTs/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,recife - pe,23/04/2026 às 14:50,244068283,"prezado, boa tarde!\n\nsobre sua manifestação,..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/demora-na-baixa-da-alienacao-fiduciaria-de-veiculo-apos-quitacao-impedindo-a-venda-e-causando-prejuizos_Y0gNWx6DvTlAg0Rb/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,são paulo - sp,23/04/2026 às 09:36,243880825,"olá, camila.\n\nesperamos que esteja bem :)\n\..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/exigencia-de-devolucao-de-valores-de-consorcio-cancelado-e-retido-indevidamente_NyzPoAlqNkYRtRE-/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,cubatão - sp,17/04/2026 às 13:14,243979377,"thais, boa tarde!\n\nesclarecemos que a devolu..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/contestacao-de-contrato-de-consorcio-nao-autorizado-e-cobranca-indevida-no-aplicativo-itau_7kre3_upx489R9Yb/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,são paulo - sp,20/04/2026 às 08:34,243948207,"prezado,\n\nprimeiramente, agradecemos a oport..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-banco-itau-cobranca-de-taxas-e-demora-na-devolucao-de-valores-apos-cancelamento_6C7f6ZD_t3XNI_CN/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,são paulo - sp,17/04/2026 às 17:49,243943877,"olá iara, esperamos que esteja bem :)\n\nescla..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/fui-pressionado-a-fechar-consorcio-de-investimento-e-fiquei-sem-dinheiro-quero-meu-valor-total-de-volta_VisttT3dG9C7n3QR/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,belo horizonte - mg,17/04/2026 às 13:20,243818541,"olá valcir, bom dia!\n\nesclarecemos que a dev..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cobranca-de-multa-e-juros-apos-reativacao-de-consorcio-sem-aviso-previo_oD31Vqlf2tUWHFO1/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,são paulo - sp,19/05/2026 às 10:46,243818311,"olá, edson!\n\nrecebemos sua manifestação e co..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cancelamento-de-consorcio-itau-por-atraso-no-pagamento-de-boleto-nao-recebido_E1iGwuvQFfbDVS-a/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,rio de janeiro - rj,17/04/2026 às 13:33,243802321,"olá joão, boa tarde!\n\nsobre sua manifestação..."

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/solicitacao-de-informe-de-rendimentos-unificado-de-cotas-de-consorcio-nao-atendida-pelo-banco-itau_IycfU66mCZLYIYHO/...
Dados enviados com sucesso!

,link,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,https://www.reclameaqui.com.br/consorcio-fiat-...,None,brasília - df,13/04/2026 às 12:17,243255325,olá fabiano!\n\n\nrecebemos sua manifestação s...