In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd
import time

# Corrigido aqui 👇
service = Service(ChromeDriverManager().install())
driver = webdriver.Chrome(service=service)

import time
import random
import undetected_chromedriver as uc

from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import StaleElementReferenceException

driver = uc.Chrome(version_main=148)
wait = WebDriverWait(driver, 15)

In [2]:
import time
import random
import undetected_chromedriver as uc

from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

driver = uc.Chrome(version_main=148)
wait = WebDriverWait(driver, 15)

dados = []
lista = [
    "https://www.reclameaqui.com.br/consorcio-fiat-e-itau/demora-excessiva-e-falta-de-informacao-no-processo-de-transferencia-de-titularidade-de-consorcio-resultando-em-risco-de-perda-de-negocio_I4xiLCnb0Tc8Uqfx/"
]
try:
    for url in lista:
        print(f"Acessando {url}...")
        driver.get(url)

        wait.until(
            EC.presence_of_all_elements_located((By.TAG_NAME, "p"))
        )

        time.sleep(random.uniform(3, 6))

        elementos = driver.find_elements(By.TAG_NAME, "p")

        for el in elementos:
            texto = el.text.strip()
            if texto and len(texto) > 10:
                dados.append({
                    "texto": texto
                })
finally:
    driver.quit()

display(dados)

Acessando https://www.reclameaqui.com.br/consorcio-fiat-e-itau/demora-excessiva-e-falta-de-informacao-no-processo-de-transferencia-de-titularidade-de-consorcio-resultando-em-risco-de-perda-de-negocio_I4xiLCnb0Tc8Uqfx/...

WebDriverException: Message: unknown error: cannot determine loading status
from target frame detached
  (Session info: chrome=148.0.7778.179)
Stacktrace:
	undetected_chromedriver!GetHandleVerifier [0x36b593+105d3]
	undetected_chromedriver!GetHandleVerifier [0x36b6c4+10704]
	undetected_chromedriver!(No symbol) [0x171cde]
	undetected_chromedriver!(No symbol) [0x161da3]
	undetected_chromedriver!(No symbol) [0x160028]
	undetected_chromedriver!(No symbol) [0x160876]
	undetected_chromedriver!(No symbol) [0x16db55]
	undetected_chromedriver!(No symbol) [0x17f48e]
	undetected_chromedriver!(No symbol) [0x1854e6]
	undetected_chromedriver!(No symbol) [0x160efc]
	undetected_chromedriver!(No symbol) [0x17ed19]
	undetected_chromedriver!(No symbol) [0x1fac4b]
	undetected_chromedriver!(No symbol) [0x1dd516]
	undetected_chromedriver!(No symbol) [0x1b08e9]
	undetected_chromedriver!(No symbol) [0x1b16a4]
	undetected_chromedriver!GetHandleVerifier [0x5f3014+298054]
	undetected_chromedriver!GetHandleVerifier [0x5ee603+293643]
	undetected_chromedriver!GetHandleVerifier [0x60ea05+2b3a45]
	undetected_chromedriver!GetHandleVerifier [0x3854e8+2a528]
	undetected_chromedriver!GetHandleVerifier [0x38cd1d+31d5d]
	undetected_chromedriver!GetHandleVerifier [0x373e68+18ea8]
	undetected_chromedriver!GetHandleVerifier [0x374015+19055]
	undetected_chromedriver!GetHandleVerifier [0x35d65f+269f]
	KERNEL32!BaseThreadInitThunk [0x76365d49+19]
	ntdll!RtlInitializeExceptionChain [0x77b1d83b+6b]
	ntdll!RtlGetAppContainerNamedObjectPath [0x77b1d7c1+231]
	(No symbol) [(nil)]

In [3]:
registro = {
    "ds_situacao_reclamacao": dados[0]["texto"],
    "estado_reclamacao": dados[1]["texto"],
    "data_reclamacao": dados[2]["texto"],
    "id_reclamacao": dados[3]["texto"].replace("ID: ", ""),
    "descricao_reclamacao": dados[4]["texto"]
}

display(registro)
import pandas as pd
df = pd.DataFrame([registro])
display(df)

{'ds_situacao_reclamacao': 'Não respondida',
 'estado_reclamacao': 'São Paulo - SP',
 'data_reclamacao': '21/05/2026 às 19:18',
 'id_reclamacao': '249338567',
 'descricao_reclamacao': 'Aproximadamente 40 dias dei entrada no processo de transferência da titularidade do consórcio, paguei taxa, assinei contrato. E após diversas ligações não consegui obter informação concreta sobre o processo de transferência. Não há impedimento e não conclui a transferência. Estou na eminência de perder o negócio que fiz devido essa demora.'}

,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,Não respondida,São Paulo - SP,21/05/2026 às 19:18,249338567,Aproximadamente 40 dias dei entrada no process...

In [4]:
palavras_ruins = [
# anteriores
    "Home"
    ,"na lista de melhores em Consórcios"
    ,"Compartilhe"
    ,"Está com problema com Consórcio Itaú?"
    ,"na lista de melhores em Consórcios"
    ,"Qual a posição de Consórcio Itaú?"
    ,"Confira a classificação"
    ,"Sobre"
    ,"FAQ"
    ,"Posts"
    ,"Compare"
    ,"Descontos"
    ,"Reclamar"
    ,"RA Ads"
    ,"Saiba mais"
    ,"Área do consumidor",
    "Cadastrar empresa"
    ,"Buscar descontos"
    ,"Rankings"
    ,"Melhores empresas"
    ,"Minhas Reclamações"
    ,"Detector de Site Confiável"

    # novos que você mandou
    ,"Ler reclamação completa",
    "Faça uma reclamação",
    "Compare empresas",
    "Cadastre uma empresa",
    "Área da empresa",
    "Por que estar AQUI?",
    "Responder reclamações",
    "Meus Produtos Reclame AQUI",
    "acesse aqui",
    "Institucional",
    "Fale conosco",
    "RA Educa",
    "Conheca a extensão",
    "Prêmio",
    "Blog RA",
    "Reclamar de uma empresa",
    "Quero trocar minha senha",
    "Não encontrei uma empresa",
    "Reclamei e ainda não responderam",
    "Quero cadastrar uma empresa",
    "Fale com o Reclame AQUI",
    "Termos de uso",
    "Política de privacidade",
    "Reclamações",
    "Principais problemas",
    "Banco Itaú",
    "Bancos e Financeiras - Bancos Tradicionais e D...",
    "+ 1.8 milhão de visualizações",
    "Ótimo",
    "Verificada"
    ,"Entenda como calculamos a reputação"
    ,"Política de Privacidade"
    ,"B"
    ,"Minhas reclamações"
    ,"Crie sua conta"
    ,"Ranking"
    ,"Tire suas dúvidas sobre o Reclame AQUI"
    ,"Entre em sua área restrita para administrar suas respostas aos consumidores, acesse aqui"
    ,"O site Reclame AQUI pode conter conteúdos destinados a maiores de 18 anos. Verifique a classificação indicativa."

]

df = df[~df["descricao_reclamacao"].isin(palavras_ruins)]
display(df.head(50))

,ds_situacao_reclamacao,estado_reclamacao,data_reclamacao,id_reclamacao,descricao_reclamacao
0,Não respondida,São Paulo - SP,21/05/2026 às 19:18,249338567,Aproximadamente 40 dias dei entrada no process...